# Generated by Django 5.2.12 on 2026-03-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseParasita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('imagem_resultado', models.ImageField(upload_to='resultados/')),
                ('parasita_detectado', models.CharField(max_length=100)),
                ('confianca', models.IntegerField()),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('lamina_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
